### ISSUE TITLE
Solution aspnet sometimes hangs with exception due to EBADF

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#611] opened 2021-07-19 15:01 UTC
The error log:

> /home/xuejun/mystikos/build/bin/myst exec-sgx --memory-size=1024m rootfs /app/webapp > server.output & echo $! > server.pid
timeout 180s tail -f server.output | ./client.sh
info: Microsoft.Hosting.Lifetime[0]
Now listening on: http://127.0.0.1:5050
info: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
Content root path: /
Hello World from asp.net!
Hello World from asp.net!
Hello World from asp.net!
Process terminated. Exception thrown from SocketAsyncEngine event loop: System.Net.InternalException: Exception of type 'System.Net.InternalException' was thrown. EBADF
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()
   at System.Environment.FailFast(System.String, System.Exception)
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()
   at System.Net.Sockets.SocketAsyncEngine+<>c.<.ctor>b__23_0(System.Object)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler+<>c.<.cctor>b__10_0(System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
System.Net.InternalException: Exception of type 'System.Net.InternalException' was thrown. EBADF
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()

**Comment by jxyang** [comment] 2021-07-19 19:05
Related: #587

**Comment by paulcallen** [comment] 2021-07-19 20:24
duplicate of #605

**Closed by paulcallen** 2021-07-19 20:24 UTC
