### ISSUE TITLE
failing libc tests

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#33] opened 2021-01-26 16:50 UTC
Out of 339 libc tests, 282 are passing, and 57 are failing.
Here are failing 57 tests:

/src/common/runtest.exe
/src/functional/env.exe
/src/functional/fcntl.exe
/src/functional/fscanf.exe
/src/functional/fwscanf.exe
/src/functional/ipc_msg.exe
/src/functional/ipc_sem.exe
/src/functional/ipc_shm.exe
/src/functional/popen.exe
/src/functional/pthread_cancel-points.exe
/src/functional/pthread_cancel.exe
/src/functional/pthread_cond.exe
/src/functional/pthread_mutex.exe
/src/functional/pthread_mutex_pi.exe
/src/functional/pthread_robust.exe
/src/functional/pthread_tsd.exe
/src/functional/sem_init.exe
/src/functional/sem_open.exe
/src/functional/setjmp.exe
/src/functional/spawn.exe
/src/functional/sscanf_long.exe
/src/functional/stat.exe
/src/functional/strptime.exe
/src/functional/ungetc.exe
/src/functional/utime.exe
/src/functional/vfork.exe
/src/math/fmal.exe
/src/math/lgamma.exe
/src/math/lgammaf.exe
/src/math/lgammal.exe
/src/math/lgammal.exe/src/math/log2f.exe
/src/math/powf.exe
/src/regression/daemon-failure.exe
/src/regression/execle-env.exe
/src/regression/fflush-exit.exe
/src/regression/fgetwc-buffering.exe
/src/regression/flockfile-list.exe
/src/regression/lseek-large.exe
/src/regression/malloc-brk-fail.exe
/src/regression/malloc-oom.exe
/src/regression/pthread-robust-detach.exe
/src/regression/pthread_atfork-errno-clobber.exe
/src/regression/pthread_cancel-sem_wait.exe
/src/regression/pthread_cond-smasher.exe
/src/regression/pthread_cond_wait-cancel_ignored.exe
/src/regression/pthread_create-oom.exe
/src/regression/pthread_exit-cancel.exe
/src/regression/pthread_exit-dtor.exe
/src/regression/pthread_once-deadlock.exe
/src/regression/rewind-clear-error.exe
/src/regression/rlimit-open-files.exe
/src/regression/setenv-oom.exe
/src/regression/sigaltstack.exe
/src/regression/sigreturn.exe
/src/regression/statvfs.exe
/src/regression/syscall-sign-extend.exe
/src/regression/tls_get_new-dtv.exe

**Comment by salsal97** [comment] 2021-03-09 01:38
The updated list of failing libc tests: 

MISSING SYSCALL ERRORS:
/src/functional/fcntl.exe: *** kernel panic: syscall.c(4464): myst_syscall(): unhandled syscall: SYS_fork()
/src/functional/ipc_msg.exe: *** kernel panic: syscall.c(4464): myst_syscall(): unhandled syscall: SYS_msgget()
/src/functional/ipc_sem.exe: *** kernel panic: syscall.c(4464): myst_syscall(): unhandled syscall: SYS_semget()
/src/functional/ipc_shm.exe: *** kernel panic: syscall.c(4464): myst_syscall(): unhandled syscall: SYS_shmget()
/src/functional/pthread_robust.exe: *** kernel panic: syscall.c(4464): myst_syscall(): unhandled syscall: SYS_get_robust_list()
/src/functional/utime.exe: *** kernel panic: syscall.c(4464): myst_syscall(): unhandled syscall: SYS_utimensat()
/src/regression/daemon-failure.exe: *** kernel panic: syscall.c(4464): myst_syscall(): unhandled syscall: SYS_fork()
/src/regression/fflush-exit.exe: *** kernel panic: syscall.c(4464): myst_syscall(): unhandled syscall: SYS_fork()
/src/regression/pthread_atfork-errno-clobber.exe: *** kernel panic: syscall.c(4464): myst_syscall(): unhandled syscall: SYS_fork()
/src/regression/pthread_exit-dtor.exe: *** kernel panic: syscall.c(4464): myst_syscall(): unhandled syscall: SYS_fork()
/src/regression/pthread-robust-detach.exe: *** kernel panic: syscall.c(4464): myst_syscall(): unhandled syscall: SYS_get_robust_list()


OTHER ERRORS: 
/src/common/runtest.exe
/src/functional/env.exe
/src/functional/popen.exe
/src/functional/pthread_cancel-points.exe
/src/functional/sem_open.exe
/src/functional/spawn.exe
/src/functional/sscanf_long.exe
/src/functional/stat.exe
/src/functional/strptime.exe
/src/functional/vfork.exe
/src/math/fmal.exe
/src/math/lgamma.exe
/src/math/lgammaf.exe
/src/math/lgammal.exe
/src/math/powf.exe
/src/regression/execle-env.exe
/src/regression/fgetwc-buffering.exe
/src/regression/malloc-brk-fail.exe
/src/regression/malloc-oom.exe
/src/regression/pthread_cond_wait-cancel_ignored.exe
/src/regression/pthread_create-oom.exe
/src/regression/rlimit-open-files.exe
/src/regression/setenv-oom.exe
/src/regression/sigreturn.exe
/src/regression/statvfs.exe
/src/regression/syscall-sign-extend.exe


TEST TIMES OUT/NEVER COMPLETES: 
/src/functional/pthread_cancel.exe
/src/functional/pthread_mutex.exe
/src/functional/pthread_mutex_pi.exe
/src/regression/raise-race.exe

**Comment by salsal97** [comment] 2021-03-12 02:15
Closing this issue since the information here will be tracked in https://github.com/deislabs/mystikos/issues/188

**Closed by salsal97** 2021-03-12 02:15 UTC
