### ISSUE TITLE
permission checking in Mystikos file systems

### ISSUE THREAD

**Issue by Francis-Liu** [deislabs/mystikos#484] opened 2021-06-17 19:16 UTC
Currently, in Mystikos one can create a file under a directory without write permission. For example, the following code succeeds.

```
$ cat test.c
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>

int main() {
    int ret = 0;
    if ((ret = mkdir("testdir", 0500)) < 0) {
        printf("mkdir failed\n");
        return ret;
    }
    if ((ret = creat("testdir/testfile", 0600)) < 0) {
        printf("creat failed as expected\n");
        return ret;
    }
    return ret;
}
```

Some comments from discussion.
- "So when we enable file permissions, then we will need impersonation of admin (sudo like)"
- "It would be even nicer if we can come up with a solution which both ext2fs and ramfs can share."
- "If we move path resolution out of the filesystems, it might be easier."

**Comment by paulcallen** [comment] 2021-06-21 20:05
duplicate of #183

**Closed by paulcallen** 2021-06-21 20:05 UTC
