### ISSUE TITLE
oelldb: Pending breakpoint in libmystkernel does not hit

### ISSUE THREAD

**Issue by vtikoo** [deislabs/mystikos#557] opened 2021-07-08 20:06 UTC
### Steps to repro:
```
cd tests/dotnet-sos
make run-ext2-lldb
```
On the lldb prompt:
```
b _syscall
```

**Comment by jxyang** [comment] 2021-07-12 20:49
I can't debug into `tools/myst/enc` after rebasing to OE 0.17.0

**Comment by anakrish** [comment] 2021-07-28 14:53
@vtikoo Where is `_syscall` defined?

**Comment by vtikoo** [comment] 2021-07-29 04:13
@anakrish in [kernel/syscall.c](https://github.com/deislabs/mystikos/blob/main/kernel/syscall.c#L3310). This symbol is part of libmystkernel, and is definitely called for any application.

**Comment by anakrish** [comment] 2021-07-29 13:19
Thanks @vtikoo 

I have a fix for this: https://github.com/openenclave/openenclave/pull/4197

The root cause is that Mystikos sends module (region) notifications **before** the enclave has been EINITed. 
When the module is registered, the debugger immediately resolves and sets any pending breakpoints within the module.
The SGX hardware disallows modifying contents of the page before the enclave has been committed because otherwise the measurement of the enclave will change. As a result the breakpoints for the region remain unresolved.

Can you try out the fix in the PR?
The ideal fix, which we can attempt later, would be to rework the order of debugger notifications in Mystikos so that the debugger is notified of modules **after** the enclave has been EINITed.

**Comment by paulcallen** [comment] 2021-11-22 21:09
fix checked in by Anand

**Closed by paulcallen** 2021-11-22 21:09 UTC
Labels: status/triaged, severity/low, area/tooling
