### ISSUE TITLE
Not all hostfs operations support uid-gid impersonation

### ISSUE THREAD

**Issue by mikbras** [deislabs/mystikos#660] opened 2021-08-02 17:19 UTC
I noticed that there might be hostfs functions that do not support uid-gid impersonation.
- link - I think maybe the new link should have the right uid-gid permissions?

Also, it I don't understand why ``stat`` would need a uid-gid. Should it just be needed when creating new objects or is it needed for all functions that accept paths?

**Comment by paulcallen** [comment] 2021-08-02 20:30
duplicate of #183

**Closed by paulcallen** 2021-08-02 20:30 UTC
