### ISSUE TITLE
Error Sending information from oe_enclave to mystikos 

### ISSUE THREAD

**Issue by stdevMac** [deislabs/mystikos#1159] opened 2022-01-24 15:07 UTC
Hi guys! 

I was working in the past days and trying to send some information from oe_enclave to mystikos following the attested_tls example using `tlssrv_write` function and it compiles but breaks.

Here is my repo addresss https://github.com/stdevMac/ and the branch `example_break` is where you can reproduce it 

This is the error I am currently getting:
```
~ make run
# Kill the running instance of the TLS server before exit.
tlssrv_host: no process found
# Launch the TLS server the OE enclave
Host: Enclave path = oe_enclave/enc/tlssrv_enc.signed, Run mode = hw, server port = 17500
OE Enclave app started...
# Launch the TLS client with myst
echo "Runnig first client"
Runnig first client
/home/nethermind/mystikos/build/bin/myst exec-sgx rootfs /app/client 127.0.0.1 
Host: starting_server

 Server in enclave: Waiting for a trusted connection
Processing client number: 0
*** kernel panic: enter.c(860): myst_enter_kernel(): myst_exec() failed, ret=-2
0x1005f608e: __myst_panic()
0x1005bfd6b: myst_enter_kernel()
Makefile:17: recipe for target 'run' failed
make: *** [run] Error 139
```

Thanks in advance!

**Comment by paulcallen** [comment] 2022-01-24 21:16
can you add --strace and --etrace to the command to see if we can get more information:
`/home/nethermind/mystikos/build/bin/myst exec-sgx  --strace --etrace rootfs /app/client 127.0.0.1 `

**Comment by mikbras** [comment] 2022-01-24 21:56
Thank you @stdevMac for creating this issue.

I looked into this, based on the information you provided, and the root of the problem is that there is no file called ``/app/client`` in the ``appdir`` (so no `./appdir/app/client`).

**Comment by mikbras** [comment] 2022-01-24 22:02
The problem stems from the "app:" makefile target, that fails to build ``./appdir/app/client``.

**Comment by mikbras** [comment] 2022-01-24 22:25
Mystikos does not detect when the application path does not exist or is not an executable file. For example:

```
$ myst exec-sgx rootfs /bin/doesnotexist
```

This causes a panic rather than reporting the ``/bin/doesnotexist`` does not exist.

**Comment by mikbras** [comment] 2022-01-24 22:46
Created issue #1163.

**Comment by mikbras** [comment] 2022-01-24 22:48
Opened PR #1162.

**Comment by mikbras** [comment] 2022-01-24 22:49
The procedure for compiling ``client.c`` above does not update the actual Docker image, so ``/app/client`` is not included in the Docker image, so ``appbuilder`` does not contain the client executable.

**Comment by stdevMac** [comment] 2022-01-26 20:30
Hi, Thanks @mikbras for the answer, did you manage to make work the example at some point?

**Comment by paulcallen** [comment] 2022-02-28 21:08
Sounds like this was a build problem you were having. I'm going to close this. If this is still an issues please reactivate.

**Closed by paulcallen** 2022-02-28 21:08 UTC
